### ISSUE TITLE
Hi - @GitHubBot developer

### ISSUE THREAD

**Issue by Helias** [zhukov/test-repo#20]
I don't know how to reach you in another way, so I am opening an issue here to start talking about this.

I am using really a lot the telegram bot @githubbot, but now I am encountering an issue about "topics", the github bot can't send messages in specific topic but it sends always in the main chatid topic the #General default one.

Fixing this issue should not be hard, it matters of sending the parameter `message_thread_id=` using the `sendMessage` API specifying the message_thread_id of the topic.

Unfortunately, the github bot is not open-source so I can't directly work on it and propose a PR, but I would like to do it.
Moreover, something that I strongly to suggest is adding a reference of the author in the @githubbot about description.

**Comment by infra-blue** [comment]
++1

**Comment by Picred** [comment]
+1

**Comment by Helias** [comment]
@zhukov ?

**Comment by zhukov** [comment]
test

**Comment by zhukov** [comment]
Added support for threads.

**Comment by Helias** [comment]
thank you a lot!
